[package]
org = "wso2"
name = "shopify_to_slack"
version = "0.1.0"
distribution = "2201.7.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "http"
version = "2.9.2"
