openapi: 3.0.1
info:
  title: HelloWorld
  description: API Definition of HelloWorld
  version: 1.0.0
servers:
- url: http://localhost:8290/HelloWorld
paths:
  /HelloWorld:
    get:
      responses:
        default:
          description: Default response
